"""
Neerav, generated by running OUR engine's prompts on his REAL intake (I act as the model).
v10 is used only for STRUCTURE (which sections, in which order). Every word of content below
is generated fresh from his intake + the real cohort retrieval — nothing copied from the v10 PDF.
Cohort (from your corpus): n=491 elite-admits in business/soc-sci/humanities — venture 35%,
service 60%, research 51%, internship 44%, debate 26%.
"""
import os, sys, json
sys.path.insert(0, os.path.dirname(__file__))
from compass import render

plan = {
 "cover": {"student": "Neerav U.", "grade": "8", "prepared": "September 2026", "family": "U.", "date": "Sept 16, 2026"},

 # ---- STEP 1: PROFILE agent, run on his intake ----
 "profile": {
   "title": "About Neerav.",
   "lead": "An 8th grader who already runs his own business and thinks by debating. The plan points those two strengths at one destination — business, law, or public affairs — within a budget and a schedule that stay realistic.",
   "blocks": [
     {"subhead": "The one thread: he runs a real business, and he thinks by debating.",
      "thesis": "Two instincts pointing the same way — toward business, law, and public affairs.",
      "body": "Neerav started his business on his own, without anyone assigning it: collectible cards now, an in-game marketplace before, with real customers and a few thousand dollars a year. In his own words, the goal is to find cards worth holding until they can cover a semester of tuition. He thinks the way he trades — taking a question from politics or business apart and running it 'this way versus that way,' comparing outcomes and strategies. Running through both is a strong sense of justice and fairness, which is why this thread points as naturally toward law and public affairs as it does toward business. It is the thread the plan is built to deepen."},
     {"subhead": "Outside the business: sports, chess, cooking, and the stage.",
      "thesis": "He competes across several areas — and tends to place when he does.",
      "body": "In sports, he has played ping-pong for the past year or two and is now considering a switch to tennis. Where he has entered competitions he has done well: medals at chess tournaments, and a top-five finish with a medal at a district-level cooking competition. He has performed in two elementary-school musicals. He also loves language, and has said he'd like to take French as an elective in college."},
     {"subhead": "How he works best: with people, a clear goal, and a route back from a mistake.",
      "thesis": "A team player who aims high, works toward a goal, and keeps going.",
      "body": "His parent describes him as creative, kind, and a leader — socially adept, quick to make friends, and often the one others seek out. Getting along with people that easily is what makes him work well in a group, and he strongly prefers that to working alone: he learns by listening and talking a problem through. Being a listener is what makes him clear when he speaks, and being the one people come to is what puts him in a position to lead them. He works best toward visible milestones — he keeps a clear goal in view and moves steadily toward it — and he aims high, holding his own work to a standard he sets himself. When he's given a route back from a mistake, like a retake or a second attempt, he takes it rather than settling for the first result, and a little encouragement is usually all it takes to get him going again."},
     {"subhead": "What's working in his favor — and what shapes the choices.",
      "thesis": "A strong academic household, a first-generation-American background, and a clearly defined budget.",
      "body": "There is real academic depth at home: his mother is a Columbia University graduate and his stepfather is a scientist at Stanford — which, among other things, makes him a legacy applicant at Columbia. He is a first-generation American, and his parent describes him as open-minded across cultures; he has travelled to India, France, and on safari in Africa, and wrote about the India trip himself. The family has also been clear about what shapes the choices: an activities budget of about $2,000–$5,000 a year with financial aid an important priority, and a preference for regional, in-person programs over travel-heavy or steep per-session ones. The plan is built to sit comfortably inside that."}],
   "flags": "Neerav is in 8th grade, so there is no transcript, GPA, or test score yet — every academic figure in this plan is a target to aim toward, not a result. The family also shared two things the calendar should account for: ADHD mentioned as a possibility rather than a diagnosis, which is why the plan keeps structure and milestones clear; and a spring allergy season of about two months that affects his energy, which is why that stretch is kept lighter. Both shape when things happen, not whether."
 },

 # ---- STEP 7 (WRITER): the VISIBLE OUTCOME CARDS.
 # Built from the gap analysis, strategy and plan. NOT the step-2 Match Key (backend-only,
 # never rendered, whose sole job is retrieving similar admitted profiles). ----
 "target": {
   "lead": "What his profile looks like at the end of grade 12 if he follows this plan. Percentages are how comparable applicants in your dataset fared at each school — cohort rates, not his personal odds.",
   "card": {"label": "TARGET PLAN · BUSINESS / LAW · CLASS OF 2031",
     "title": "The founder who took debate to state.",
     "subtitle": "Five years running his own business; one format to a state qualification, with the squad behind him.",
     "stats": [{"k": "GPA (target)", "v": "3.8+", "sub": "UW"}, {"k": "Testing floor", "v": "1500+", "sub": "/ 34+"},
               {"k": "Rigor", "v": "6–8", "sub": "APs, paced"}, {"k": "Math ceiling", "v": "Calc", "sub": "by 12th"}],
     "credentials": [
       {"h": "State-qualifying debater, captain of the squad.", "t": "Three years in one format on the California circuit, a state qualification in junior year, and captain of his school team as a senior."},
       {"h": "A registered business — and an internship that used it.", "t": "The resale venture formalised and filing, plus a summer at a local business or nonprofit doing real pricing and negotiation work."},
       {"h": "Food-security volunteering, led with his cooking.", "t": "Four years with one organization, moving from shifts to running a cooking-based program of his own inside it."},
       {"h": "Model UN delegate, with an award.", "t": "Two years on the conference circuit and a committee or delegation award — his politics interest, made competitive."}],
     "within_reach": "Target 35–60% UC Berkeley · UCLA · Michigan · UVA · USC · Likely 60%+ UC Davis · UCSB · San José State",
     "toughest": "Reach 15–35% Cornell · UPenn · Brown · Georgetown · Far reach <15% Harvard · Yale · Princeton · Stanford",
     "takeaway": "A self-built profile that puts the strong publics — Berkeley, UCLA, Michigan — genuinely in range, with the Ivies as an honest long shot rather than the plan."},
   "bands": {"intro": "TARGET PLAN — how comparable applicants in your dataset fared, from a cohort of 491 in his direction. Cohort rates, not personal odds.",
     "bands": [
       {"name": "Far Reach", "range": "< 15%", "colleges": [{"name": "Harvard"}, {"name": "Yale"}, {"name": "Princeton"}, {"name": "Stanford"}]},
       {"name": "Reach", "range": "15–35%", "colleges": [{"name": "Cornell"}, {"name": "UPenn"}, {"name": "Brown"}, {"name": "Georgetown"}]},
       {"name": "Target", "range": "35–60%", "colleges": [{"name": "UC Berkeley"}, {"name": "UCLA"}, {"name": "Michigan"}, {"name": "UVA"}]},
       {"name": "Likely", "range": "60%+", "colleges": [{"name": "UC Davis"}, {"name": "UC Santa Barbara"}, {"name": "San José State"}]}]}
 },

 "stretch": {
   "lead": "The same two threads, pushed earlier and harder. The stronger profile moves most schools up a band.",
   "card": {"label": "STRETCH PLAN · BUSINESS / LAW · CLASS OF 2031",
     "title": "The founder who took debate to nationals.",
     "subtitle": "A competition-placed business, a national qualification, and the squad in his hands.",
     "stats": [{"k": "GPA (target)", "v": "3.9–4.0", "sub": "UW"}, {"k": "Testing floor", "v": "1500+", "sub": "/ 34+"},
               {"k": "Rigor", "v": "9–11", "sub": "APs"}, {"k": "Math ceiling", "v": "Calc", "sub": "by 11th"}],
     "credentials": [
       {"h": "Top-ten debater in the country, captain from junior year.", "t": "A national qualification with a signature result attached to his name, and running the squad two years early."},
       {"h": "A registered business, and a substantive internship.", "t": "The venture scaled with documented revenue and a pitch-competition placing, alongside a real role at an established organization."},
       {"h": "Founded the cooking programme he volunteers in.", "t": "A cooking-based food-security initiative of his own inside a partner organization, with other students working under him."},
       {"h": "Best Delegate at a national Model UN conference.", "t": "The public-affairs thread taken from local conferences to a national award."}],
     "within_reach": "Target 35–60% Cornell · UPenn · Georgetown · Likely 60%+ UC Berkeley · UCLA · Michigan",
     "toughest": "Reach 15–35% Harvard · Yale · Princeton · Stanford · + a possible international route (UK PPE-style programs suit a live arguer)",
     "takeaway": "The stronger profile moves the most selective schools from long shots into real reaches, and opens an international route built on live argument."},
   "bands": {"intro": "STRETCH PLAN — most schools move up one band · the in-state anchors stay likely.",
     "bands": [
       {"name": "Far Reach", "range": "< 15%", "colleges": []},
       {"name": "Reach", "range": "15–35%", "colleges": [{"name": "Harvard", "up": True}, {"name": "Yale", "up": True}, {"name": "Princeton", "up": True}, {"name": "Stanford", "up": True}]},
       {"name": "Target", "range": "35–60%", "colleges": [{"name": "Cornell", "up": True}, {"name": "UPenn", "up": True}, {"name": "Georgetown", "up": True}]},
       {"name": "Likely", "range": "60%+", "colleges": [{"name": "UC Berkeley", "up": True}, {"name": "UCLA", "up": True}, {"name": "Michigan", "up": True}, {"name": "UC Davis"}, {"name": "UCSB"}]}]}
 },

 # ---- STEP 6 (course targets), generated from the plan ----
 "course": {
   "lead": "The course level to aim for when he picks classes — both plans, side by side. These are targets to select toward, since he hasn't started high school, not grades he holds.",
   "target_gpa": "3.8+ UW", "stretch_gpa": "3.9–4.0 UW",
   "target_bullets": ["Land advanced-math placement now so calculus by 12th is on the table",
                      "Honors where his school offers it, on a paced AP arc", "A relaxed PSAT baseline in 9th — no testing pressure yet"],
   "stretch_bullets": ["Math a year ahead — calculus by 11th",
                       "The social-science APs that match his direction (Gov, Econ, US History)", "French pushed toward AP, with rigor front-loaded so spring stays light"],
   "table": [
     {"track": "Math", "target": "On-level → Calculus by 12th", "stretch": "Accelerated → Calculus by 11th + Statistics"},
     {"track": "Social science (his lane)", "target": "Honors; AP Gov / AP Econ in the upper years", "stretch": "AP Gov, AP Econ, AP US History, + a comparative AP"},
     {"track": "English", "target": "Honors English", "stretch": "Honors into AP Language & Literature"},
     {"track": "Science", "target": "College-prep sequence", "stretch": "Honors + one AP"},
     {"track": "World language", "target": "French through level 3–4", "stretch": "French through AP"},
     {"track": "AP total (9–12)", "target": "6–8, paced for his energy", "stretch": "9–11, front-loaded but protecting spring"}],
   "note": "One thing the Top-10 data makes clear: academics are a floor, not a differentiator — clear roughly 1500+/3.8+ and that's enough; pushing scores past ~1550 doesn't add much, and a full course load without one clear standout tends not to stand out on its own. So aim these targets, protect the GPA, and put the extra energy into debate and the business. First job this fall: confirm his 8th-grade math placement (it sets his whole math ceiling) and check whether his school uses AP labels. Keep the spring allergy months light — no rigor jump into them."
 },

 # ---- STEP 5/6: STRATEGY → roadmap goals & tasks, generated for a two-home, budget-limited, perfectionist kid ----
 "roadmap": {
   "title": "Grade 8 to 12: try a little, then go deep.",
   "lead": "The Top-10 data is blunt about this: depth beats breadth, and one genuine high-tier \"spike\" is what moves an applicant up a band — admits actually list fewer activities than rejects. For his lane (business / social science) that spike is debate plus a documented venture, not a long résumé. So the arc is: test a few things this year, keep what's genuinely his, and take that small set to a real level. Five years, three stages, and he's at the start.",
   "stages": [
     {"grade": "GRADE 8–9", "name": "Try & keep", "body": "Sample the kinds of argument competition and confirm which activities are really his. Build the study habits that a 3.8 needs.", "color": ""},
     {"grade": "GRADE 10", "name": "Commit", "body": "Pick the one debate format he's best at, put real results on the business, and gently narrow to the few things he most wants to take further.", "color": "g"},
     {"grade": "GRADE 11–12", "name": "Go deep", "body": "Leadership, a standout result, a documented business, and an application built around one clear story.", "color": "p"}],
   "grades": [
     {"grade": "Grade 8", "years": "2026–27 · YOU ARE HERE", "tag": "Test a few things; keep the base light.", "rows": [
       {"title": "Sample argument, don't commit to a format.", "tasks": [
         {"term": "Fall", "text": "Get into one low-pressure class or club that exposes him to a few argument formats, so he can feel out which suits him."},
         {"term": "Spring", "text": "One small, first competition in whichever format he liked — a single event, timed away from allergy season."}]},
       {"title": "Make the business real on paper.", "tasks": [
         {"term": "Fall", "text": "Start a simple record of what it earns and sells, and take it to a real, one-day selling event — the proof it happens outside school."}]},
       {"title": "One genuine cause — and one he can bring a skill to.", "tasks": [
         {"term": "Fall →", "text": "Start recurring, flexible-shift volunteering the family can do together at a food-security organization. He cooks and competes at it, so this is the cause where his own skill can eventually become the contribution rather than just his time."}]},
       {"title": "Lock the academic runway for 9th.", "tasks": [
         {"term": "Fall–Winter", "text": "Get the advanced-math placement sorted and set steady study habits now, before 9th, when grades start counting."}]}]},
     {"grade": "Grade 9", "years": "2027–28", "tag": "Grades count; start to focus.", "rows": [
       {"title": "Protect a 3.8+ from day one.", "tasks": [
         {"term": "All year", "text": "Honors where it fits, real study routines, a low-stakes PSAT 8/9 — this is the first year the transcript matters."}]},
       {"title": "Find his best argument format.", "tasks": [
         {"term": "All year", "text": "Join the high-school team and rotate through a couple of formats to see where he actually shines."}]},
       {"title": "Keep growing — and writing up — the business.", "tasks": [
         {"term": "All year", "text": "Push it one real step further and start keeping the story of what it's done."}]},
       {"title": "Add Model UN alongside debate.", "tasks": [
         {"term": "All year", "text": "Join the school's Model UN club — the same argument skill aimed at politics and policy, and a second circuit to compete on."}]}]},
     {"grade": "Grade 10", "years": "2028–29", "tag": "Commit to the few that are working.", "rows": [
       {"title": "Choose and consolidate.", "tasks": [
         {"term": "Fall", "text": "Commit to one debate format and the business; drop the rest; first AP classes; hold the GPA."}]},
       {"title": "Get results on the business.", "tasks": [
         {"term": "All year", "text": "Set a concrete growth target and enter one entrepreneurship or pitch competition; write down the outcome."}]},
       {"title": "Take a real role in his cause.", "tasks": [
         {"term": "All year", "text": "Move from helper to a defined responsibility in the group he's stuck with — depth, not a title."}]},
       {"title": "Register the business — and get inside a real organization.", "tasks": [
         {"term": "Fall", "text": "Register the venture properly and start filing. An informal cash business carries little weight on an application; a registered one that files is a different object entirely."},
         {"term": "Summer '29", "text": "Place him in a real internship at a local business or nonprofit where his pricing, sourcing and negotiation experience is actually used — this is what turns his entrepreneurial skill into something an admissions reader can verify."}]}]},
     {"grade": "Grade 11", "years": "2029–30 · THE FOCUS YEAR", "tag": "Lead, qualify, and test.", "rows": [
       {"title": "Lead and earn a signature result.", "tasks": [
         {"term": "All year", "text": "Captain or officer; qualify at the state or national level in his format."}]},
       {"title": "The business at its peak.", "tasks": [
         {"term": "All year", "text": "Its clearest, best-documented year — the real thing grown, not a project invented for applications."}]},
       {"title": "Hardest courses and the one test cycle.", "tasks": [
         {"term": "All year", "text": "Several APs; a diagnostic to pick SAT or ACT, then aim for the 1500 / 34 floor."}]},
       {"title": "Set the application story before writing.", "tasks": [
         {"term": "Summer '30", "text": "Shape the arc — founder, arguer, first-generation American — and draft the main essay; open the international route early if it's on."}]}]},
     {"grade": "Grade 12", "years": "2030–31", "tag": "Apply and choose on aid.", "rows": [
       {"title": "Apply cleanly, finish strong.", "tasks": [
         {"term": "Fall", "text": "Finalize the list; early applications where they help; recommenders lined up; essays already drafted."},
         {"term": "Spring", "text": "Compare offers and aid packages — aid is essential — chase outside scholarships, and choose."}]}]}]
 },

 # ---- STEP 6: GRADE 8 deep dive — recommendations generated at the engine's current (category) capability ----
 "this_year": {
   "title": "Grade 8, term by term.",
   "lead": "His grade-8 year in three terms — Fall, Spring, Summer — each with the exact program, cost, age fit, and how to sign up. Debate is his spine, so it runs across all three: a class in the fall, one competition in the spring, and a focused program in the summer.",
   "terms": [
     {"term": "Fall 2026", "dates": "AUG–DEC · NOW", "tag": "Start debate; sell at a fair; set up the year.",
      "intro": "Four moves this term. Two are time-sensitive — the debate class and the business fair.",
      "cards": [
        {"cat": "Debate", "cat_class": "debate", "title": "Start his debate spike — Little Loudspeakers (San José)", "act": "ACT NOW",
         "body": "Debate is his one spike, so it's the priority and it starts now, low-stakes. It also fits how he works: debate is a squad activity — you prep with partners, travel as a team, and coach each other — so it puts his strongest social skills to work rather than asking him to compete alone, and it turns the communication ability he already has into a result an admissions reader can see. The primary pick is Little Loudspeakers Academy in San José: their \"Debate for 8–14 yrs, Fall 2026\" class is his exact age, and it's offered in-person (1040 Park Ave, San José) or online, which fits a busy week. It samples several speech/debate styles before he commits to one.",
         "options": ["<strong>Primary — Little Loudspeakers, San José.</strong> \"Debate for 8–14 yrs, Fall 2026\" — ages 8–14, a clean fit for a 13-year-old; in-person or online.",
                     "<strong>Free alternative — his school team.</strong> Ask Sierramont whether it fields a speech/debate team; Bay-Area school teams compete on the Golden Gate Speech Association / Coast Forensic League circuits, and he'd move onto the CHSSA high-school circuit in 9th grade."],
         "contact": "Little Loudspeakers · (408) 904-9649 · littleloudspeakers.com — call for the current fall price (not posted online).",
         "plan_by": "This week — fall classes are already running; call to confirm the price and enroll.", "note": None},
        {"cat": "Venture", "cat_class": "venture", "title": "Sell at the San José Children's Business Fair", "act": "ACT NOW",
         "body": "A real one-day fair with customers and judges for his collectibles business — the outside-school proof the admissions data rewards. Two Bay-Area registration dates are open: Oct 3 and Oct 17 (Santa Clara). The Oct 17 Santa Clara fair has a $50 booth fee.",
         "options": [], "contact": "childrensbusinessfair.org/cities/san-jose-ca-usa",
         "plan_by": "Mid-September — register now for Oct 3 or Oct 17; booths fill. Start a simple sales ledger the same week.", "note": None},
        {"cat": "Service", "cat_class": "service", "title": "Book a family shift at Second Harvest", "act": "ACT NOW",
         "body": "Second Harvest of Silicon Valley (San José) takes family volunteers on single, flexible shifts — which works around two homes. It's the cause the family already wanted; keep it genuine and recurring (and from the data, it's for its own sake, not an admissions lever).",
         "options": [], "contact": "shfb.org/give-help/volunteer — San José, within ~10 miles.",
         "plan_by": "Late September — book an October shift from their volunteer calendar.", "note": None},
        {"cat": "Academics", "cat_class": "academics", "title": "Book the school counseling meeting", "act": "ACT NOW",
         "body": "Free, through Sierramont. Confirm his 8th-grade math placement (it sets his whole high-school math ceiling) and get the course catalog, so 9th-grade selection in the spring isn't a scramble.",
         "options": [], "plan_by": "Early October — before course selection opens.", "note": None}]},
     {"term": "Spring 2027", "dates": "JAN–MAY", "tag": "One competition; choose 9th-grade courses.",
      "intro": "The debate class continues; he enters one first competition, and you lock the 9th-grade schedule. Spring is his allergy season (Feb–April), so it's exactly one event.",
      "cards": [
        {"cat": "Debate", "cat_class": "debate", "title": "His first novice tournament — exactly one", "act": "PLAN AHEAD",
         "body": "After a fall semester of class, one beginner tournament — entered through Little Loudspeakers or his school team, so he never signs up alone. A single event, scheduled around his Feb–April allergy window.",
         "options": [], "contact": "through Little Loudspeakers · (408) 904-9649, or his school coach.",
         "plan_by": "January — ask his coach which novice event fits, then enter a few weeks before it closes.", "note": None},
        {"cat": "Academics", "cat_class": "academics", "title": "Lock the 9th-grade schedule", "act": "PLAN AHEAD",
         "body": "Course selection usually runs January–March. Choose the runway from the fall counseling meeting — advanced math toward calculus, honors where offered, French — and keep the monthly Second Harvest shift going.",
         "options": [], "plan_by": "January–March, when selection opens.", "note": None}]},
     {"term": "Summer 2027", "dates": "JUN–AUG", "tag": "One focused debate program.",
      "intro": "Debate class runs during the school year, so the summer is one focused program to consolidate his spike before high school — inside the $3,000–$5,000 summer budget.",
      "cards": [
        {"cat": "Summer program", "cat_class": "debate", "title": "A summer public-speaking / debate session — Little Loudspeakers", "act": "PLAN AHEAD",
         "body": "The natural summer move is to deepen the one spike: keep him with Little Loudspeakers (same academy, same 8–14 age band, San José or online) for their summer public-speaking / debate session. A short, focused block over the summer builds his confidence for the high-school circuit in 9th.",
         "options": [], "contact": "Little Loudspeakers · (408) 904-9649 · littleloudspeakers.com",
         "plan_by": "the winter check-in (Dec–Jan) — call then to confirm they're running a summer 2027 session, get the dates and price, and enroll early as low-cost seats fill.",
         "note": "Keep the rest of the summer light — this is the one focused program. Tennis, chess, and cooking can continue alongside as he enjoys them."}]}]
 },

 # ---- STEP 7 close: PARENT ACTIONS, ordered by deadline ----
 "parent_actions": {
   "lead": "Everything above, ordered by deadline with a few weeks of slack built in. None of it leans on Neerav — it's setup, so his week stays light.",
   "items": [
     {"n": 1, "when": "This week", "text": "Get him into debate — his spike. Call Little Loudspeakers in San José (408) 904-9649 to enroll in their \"Debate for 8–14 yrs, Fall 2026\" class and confirm the price; or ask Sierramont whether it has a school team (which would compete on the Golden Gate Speech Association / Coast Forensic League circuits). Fall classes are already running."},
     {"n": 2, "when": "By mid-September", "text": "Register for the San José Children's Business Fair — Oct 3 or Oct 17 (Santa Clara, $50 booth) at childrensbusinessfair.org/cities/san-jose-ca-usa. Open a shared spreadsheet with him to start logging the business."},
     {"n": 3, "when": "By late September", "text": "Book a family shift at Second Harvest of Silicon Valley (shfb.org/give-help/volunteer, San José) for October — single flexible shifts work around two homes."},
     {"n": 4, "when": "By early October", "text": "Book the counseling meeting; confirm 8th-grade math placement and request the course catalog before selection opens."},
     {"n": 5, "when": "By January", "text": "Through his Little Loudspeakers class or school coach, pick one spring novice tournament and enter a few weeks before it closes."},
     {"n": 6, "when": "Winter check-in (Dec–Jan)", "text": "Call Little Loudspeakers to confirm their summer 2027 session, dates, and price; book early. Revisit this plan while you're at it."},
     {"n": 7, "when": "February–April", "text": "Keep allergy season light — schoolwork and the one planned event, without adding anything new that stretch."},
     {"n": 8, "when": "Ongoing", "text": "Let tennis, chess, and cooking continue as he enjoys them, and keep some regular downtime in his week."},
     {"n": 9, "when": "This spring", "text": "No pressure — if it feels useful, a pediatrician conversation about the ADHD question could later open up accommodations he'd be entitled to."}]
 },

 "final_note": [
   "You asked what he should do now, and this summer, to head toward a college that leads to business, law, or public affairs — and you were clear that you'd rather he do a few things really well than spread himself thin. This plan is built exactly that way: focused on purpose, and that focus is the strategy.",
   "He already owns the two things that are hardest to build from scratch — a business he runs himself and a mind that argues to understand. The next four years aren't about adding more; they're about taking those two things deep, keeping the budget and schedule realistic, and protecting the downtime that keeps him at his best. Given a clear focus and steady support, a driven kid like this builds real momentum — he compounds."]
}

out = os.path.join(os.path.dirname(__file__), "out", "neerav_plan.pdf")
render.to_pdf(plan, out)
json.dump(plan, open(out.replace(".pdf", ".plan.json"), "w"), indent=2)
print("✓ rendered", out)
